/* Lab content — placeholder but plausible for a Building Engineering group */

const LAB = {
  name: "Ye's Research Group",
  shortName: "YRG",
  university: "Colorado School of Mines",
  department: "Department of Civil and Environmental Engineering",
  location: "Coolbaugh Hall Room 310A, Golden, CO",
  email: "yunyang.ye@mines.edu",
  established: 2023,
};

const MANIFESTO = [
  "We design buildings that breathe,",
  "sense, and adapt —",
  "envelopes as living systems",
  "between climate and occupant.",
];

const RESEARCH_AREAS = [
  {
    code: "R-01",
    title: "1947-RP: Climate Change Driven Extreme Temperature Effects for Efficiency and Resilience Map of Heat Pump Technology",
    summary: "Developing efficiency and resilience maps for heat pump technology under climate-change-driven extreme temperature conditions across diverse U.S. climate zones.",
    extended: "The overall objective is to understand better building resilience issues associated with air-conditioning to climate change and extreme weather events (e.g., heat waves and cold snaps), and the climate change-driven extreme temperature effects for efficiency and resilience map of heat pump technology across the U.S. This proposed project intends to:",
    extendedBullets: [
      "Systematize the process of running building energy models with a wide range of future weather files.",
      "Create an easy-to-understand way to store and visualize the simulation results for building resilience.",
      "Support the improvement of ASHRAE Standards to guide the enhancement of future building resilience against climate change with extreme weather events.",
    ],
    tags: ["Heat Pumps", "Climate Resilience", "Energy Efficiency"],
    sponsor: ["ASHRAE"],
    sponsor_extended: ["American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE)"],
    collaborator: [],
    image: "assets/research/R-01.jpg",
  },
  {
    code: "R-02",
    title: "RII Track-2 FEC: Transforming Wastes into Economic Assets for Sustainability, Resilience, and Prosperity by Novel Negative Emission Technology",
    summary: "A multi-institution NSF initiative developing novel negative-emission technologies that convert waste streams into economic assets while advancing regional sustainability and resilience.",
    extended: "This project intends to use Negative Emission Technology to convert hazardous industrial wastes into low-cost, low-carbon construction materials, generating economically viable pathways to enhance the climate resilience of disadvantaged communities. This project includes partnerships across Alabama, Idaho and New Mexico.",
    link: { label: "NSF Announcement", url: "https://new.nsf.gov/news/nsf-announces-77-8m-investment-build-epscor" },
    tags: ["Carbon Capture", "Sustainability", "Circular Economy"],
    sponsor: ["U.S. NSF"],
    sponsor_extended: ["U.S. National Science Foundation (NSF)"],
    collaborator: ["University of Idaho", "University of New Mexico", "Alabama A&M University"],
    image: "assets/research/R-02.jpg",
  },
  {
    code: "R-03",
    title: "Development and Implementation of Occupant-Centric Control Strategy in Residential Prototype Building Models",
    summary: "Designing and validating occupant-centric building control strategies within DOE residential prototype models to improve comfort, energy efficiency, and grid flexibility.",
    extended: "Occupancy behaviors significantly affect energy consumption in residential buildings, and occupant-centric controls are a promising way to save residential building energy. New editions of building energy codes have increased requirements for occupant-centric controls to encourage residential building performance improvement. The U.S. Department of Energy and Pacific Northwest National Laboratory developed Residential Prototype Building Models to analyze the performance of residential building energy codes and standards. The current models adopt oversimplified occupant-centric control strategies. These strategies must be implemented in the Residential Prototype Building Models to analyze complex occupant-centric control strategies in residential buildings. This project aims to understand occupancy behavior, develop an occupant-centric control strategy, and implement an occupancy-centric control strategy in the Residential Prototype Building Models.",
    tags: ["Occupant Comfort", "Building Controls", "Energy Modeling"],
    sponsor: ["U.S. DOE"],
    sponsor_extended: ["U.S. Department of Energy (DOE)"],
    collaborator: ["Pacific Northwest National Laboratory"],
    image: "assets/research/R-03.jpg",
  },
];

const MEMBERS = [
  {
    id: "ye",
    name: "Yunyang Ye",
    role: "Principal Investigator",
    title: "Assistant Professor",
    field: "Building Science",
    joined: 2023,
    pronouns: "he/him",
    blurb: "Studies the thermodynamics of occupied space — how buildings quietly negotiate between weather, bodies, and the grid. Founded the lab in 2023.",
    interests: ["Sustainable Buildings from Micro to Macro Scales", "Resilient Buildings Against Climate Hazards", "Sustainable, Resilient, and Smart Cities", "Grid-Interactive Efficient Buildings", "Building Policy"],
    education: ["Ph.D. in Architectural Engineering, University of Colorado Boulder", "M.E. in Power Engineering (HVAC), Tongji University", "B.E. in Building Environmental and Facilities Engineering, Tongji University"],
    employment: ["Assistant Professor, Colorado School of Mines, 08/2025 - Present", "Assistant Professor, University of Alabama, 08/2023 - 08/2025", "Research Scientist, Paccific Northwest National Laboratory, 01/2020 - 08/2023"],
    office: "Coolbaugh Hall 310A",
    email:"yunyang.ye@mines.edu",
    profiles: [
      { label: "Google Scholar", url: "https://scholar.google.com/citations?user=B9WSzWcAAAAJ&hl=en&oi=ao" },
      { label: "ResearchGate",   url: "https://www.researchgate.net/profile/Yunyang-Ye-3" },
    ],
    initial: "Y",
    photo: "assets/people/yunyang-ye.jpg",
    professionalActivities: ["Voting Member for ASHRAE SGPC 10", "Vice Chair for ASHRAE TC7.4 Exergy Analysis for Sustainable Buildings (EXER)", 
      "Youth Editor for Building Simulation: An International Journal", 
      "Guest Editor for the Journal of Building Performance Simulation Special Issue, Building Sustainability and Performance Through Simulation", 
      "Guest Editor for the Building and Environment Special Issue, Net Zero Carbon Built Environment", 
      "Scientific Committee Member for 1st International Conference of Net Zero Carbon Built Environment",
      "Guest Editor for the Sustainability Special Issue, Sustainable Solutions for Energy-Efficient Buildings and Net-Zero Emissions", 
      "Guest Editor for the Buildings Special Issue, Achieving Carbon Neutrality in Urban Infrastructure Development", 
      "Scientific Committee Member for IBPSA-USA SimBuild 2024 Conference", 
      "Guest Editor for a Special Issue of ASHRAE's Science and Technology of the Built Environment", 
      "Leading Guest Editor for the Building Special Issue, Urban Climate, Comfort and Building Energy Performance",
      "Topical Advisory Panel Member for Buildings"],
    awards: ["ASHRAE New Investigator Award ($125,000)", "IBPSA-USA 2024 Emerging Contributor Award",
      "PNNL Early Career Researcher Award Finalist", "PNNL Outstanding Performance Award", 
      "PNNL EI&BD Mentors of the Month for July", "ASHRAE Homer Addams Award",
      "Reviewer's Recognition: 2021 Reviewers of the Year from the Journal of Solar Energy Engineering"],
  },
  {
    id: "yj",
    name: "You-Jeong Kim",
    role: "Postdoctoral Researcher",
    title: "Postdoctoral Researcher",
    field: "Building Science",
    joined: 2026,
    pronouns: "she/her",
    blurb: "Postdoctoral researcher in the lab.",
    interests: ["Building simulation", "Thermal comfort", "Climate adaptation"],
    education: ["Ph.D. in Architecture and Building Sciences/Technology, University of Illinois Urbana-Champaign", "M.S. in Architectural Engineering, Ewha Womans University", "B.S. in Architectural Engineering, Ewha Womans University"],
    employment: [],
    office: "Coolbaugh Hall 308",
    email:"youjeong.kim@mines.edu",
    cv: null,
    initial: "Y",
  },
  {
    id: "luna",
    name: "Ryunhee (Luna) Kim",
    role: "PhD Candidate",
    title: "PhD Candidate",
    field: "Civil & Environmental Engineering",
    joined: 2023,
    pronouns: "she/her",
    blurb: "Field measurement of indoor environmental quality in retrofit-heavy housing stock. Joined the lab in 2023.",
    interests: ["Heating, Ventilation and Air-Conditioning (HVAC) Systems", "Intelligent Building Energy Management System", "Occupant-Centric Building System Control and Optimization", "Fault Detection and Diagnosis (FDD) in Building Systems", "Unsupervised Data Mining for Building and Urban Energy Systems", "Automated Continuous Commissioning"],
    education: ["M.S. in Building Performance and Diagnostics, Carnegie Mellon University", "B.Eng. in Architecture and Urban Design, Incheon National University"],
    employment: [],
    office: "Coolbaugh Hall 308",
    email:"ryunhee_kim@mines.edu",
    cv: null,
    initial: "L",
    photo: "assets/people/luna-kim.jpg",
  },
  {
    id: "huawei",
    name: "Huawei Yu",
    role: "PhD Student",
    title: "PhD Student",
    field: "Civil & Environmental Engineering",
    joined: 2025,
    pronouns: "he/him",
    blurb: "Learning occupant behavior from low-resolution building sensor data. Joined the lab in 2025.",
    interests: ["Data-driven Building Energy Modeling", "Digital Twin and Smart Control for Built Environments", "Occupancy and Behavioral Pattern Modeling", "Machine Learning Applications in Building Systems", "Intelligent Building Operation and Control"],
    education: ["M.S. in Sustainable Design, Carnegie Mellon University", "M.S. in Design, Advanced Architecture Design, University of Pennsylvania", "B.Arch. in Architecture, Fuzhou University"],
    employment: [],
    office: "Coolbaugh Hall 308",
    email:"huawei_yu@mines.edu",
    cv: null,
    initial: "H",
    photo: "assets/people/huawei-yu.jpg",
  },
  {
    id: "wenxin",
    name: "Wenxin Huang",
    role: "PhD Student",
    title: "PhD Student",
    field: "Civil & Environmental Engineering",
    joined: 2026,
    pronouns: "she/her",
    blurb: "PhD student in the lab.",
    interests: ["Building Energy Efficiency", "Sustainable and Resilient Buildings", "Indoor Environmental Quality", "Smart Building Systems", "Thermal Energy Storage"],
    education: ["MSc in Health, Wellbeing and Sustainable Buildings, University College London", "B.Eng. in Environmental Engineering, Jilin University"],
    employment: [],
    office: "Coolbaugh Hall 308",
    email:"wenxin_huang@mines.edu",
    cv: null,
    initial: "W",
    photo: "assets/people/wenxin-huang.jpg",
  },
];

const ALUMNI = [
  { name: "Narjes Faghih", year: 2023, role: "PhD candidate, University of Alabama", thesis: "—" },
];

const PUBLICATIONS = [
  {
    year: 2026,
    type: "Conference",
    venue: "SimBuild '26",
    title: "Development of New Occupancy Schedules and Occupant-Centric Control Strategy for Residential Buildings",
    authors: ["R. Kim", "C. Faulkner", "Y. Chen", "Y. Ye"],
    members: ["luna", "ye"],
    doi: "—",
  },
  {
    year: 2026,
    type: "Conference",
    venue: "SimBuild '26",
    title: "Principal Variate Selection Approach for LSTM Building Load Forecasting",
    authors: ["H. Yu", "Y. Ye", "J. Xu", "Y. Shi"],
    members: ["huawei", "ye"],
    doi: "—",
  },
  {
    year: 2026,
    type: "Journal",
    venue: "Building Simulation",
    title: "An autoregressive-based framework for simulating stochastic occupant behavior in residential buildings",
    authors: ["J. Xu", "R. Kim", "Y. Ye", "Y. Shi"],
    members: ["luna", "ye"],
    doi: "10.1007/s12273-026-1406-3",
  },
  {
    year: 2026,
    type: "Journal",
    venue: "Energy Efficiency",
    title: "An assessment of electricity consumption flexibility from cabin thermal management systems in electric buses",
    authors: ["N. Faghih", "J. Bowman", "R. Kim", "Y. Ye", "K. Chen"],
    members: ["luna", "ye"],
    doi: "10.1007/s12053-026-10416-7",
  },
  {
    year: 2024,
    type: "Conference",
    venue: "SimBuild '24",
    title: "Developing A Novel Modeling Framework for Residential Home's Occupant Behaviors in Support of Building-to-Grid Integration Research",
    authors: ["R. Kim", "Y. Ye", "S. Huang", "Y. Xie", "J. Wang"],
    members: ["luna", "ye"],
    doi: "—",
  },
  {
    year: 2024,
    type: "Conference",
    venue: "2024 IEEE ISGT",
    title: "Simulation-Guided Decision-Making for Enhancing Energy Resilience in a Remote Alaskan Community",
    authors: ["S. Biswas", "C. Faulkner", "T. Wall", "F. Tuffner", "Y. Ye", "et al."],
    members: ["ye"],
    doi: "10.1109/ISGT59692.2024.10454223",
  },
  {
    year: 2024,
    type: "Journal",
    venue: "Building Simulation",
    title: "A New Database of Building-Space-Specific Internal Loads and Load Schedules for Performance Based Code Compliance Modeling of Commercial Buildings.",
    authors: ["Y. Ye", "C. Faulkner", "W. Jung", "J. Zhang", "E. Brock"],
    members: ["ye"],
    doi: "10.1007/s12273-024-1111-z",
  },
  {
    year: 2024,
    type: "Journal",
    venue: "Science and Technology for the Built Environment",
    title: "Energy Modeling of Typical Commercial Buildings in Support of ASHRAE Building Energy Quotient Energy Rating Program (ASHRAE RP-1771).",
    authors: ["Y. Lou", "Y. Ye", "Y. Yang", "W. Zuo", "G. Wang"],
    members: ["ye"],
    doi: "10.1080/23744731.2023.2299171",
  },
  {
    year: 2024,
    type: "Conference",
    venue: "SimBuild '24",
    title: "Long-Term Assessment of Commercial Building Energy and Carbon Emissions in the Northwestern Region Under Future Weather Trend",
    authors: ["Y. Yang", "J. Sui", "Y. Ye", "W. Zuo", "Y. Jung", "X. Lei"],
    members: ["ye"],
    doi: "—",
  },
  {
    year: 2024,
    type: "Conference",
    venue: "SimBuild '24",
    title: "Integration of Hourly Energy Usage and Emission Rates Through Mapping Between Climate Zones And eGrid Region",
    authors: ["Y. Xie", "Y. Jung", "J. Zhang", "Y. Ye", "Y. Chen", "V. Salcido", "D. Maddox", "E. Franconi", "M. ROsengberg"],
    members: ["ye"],
    doi: "—",
  },
];

const NEWS = [
  {
  date: "2025-02-24",
  kind: "Award",
  title: "Dr. Ye received the ASHRAE New Investigator Award",
  body: "ASHRAE recognized Dr. Ye with the New Investigator Award for contributions to building energy and sustainability research.",
  link: "https://www.ashrae.org/technical-resources/research/new-investigator-award",
  },

  {
    date: "2025-02-24",
    kind: "Funding",
    title: "Dr. Ye received new ASHRAE funding for heat pump resilience research",
    body: "The project '1947-RP: Climate Change Driven Extreme Temperature Effects for Efficiency and Resilience Map of Heat Pump Technology' was funded by ASHRAE.",
    link: "#",
  },

  {
    date: "2025-02-11",
    kind: "Conference",
    title: "Dr. Ye chaired a seminar at the 2025 ASHRAE Winter Conference",
    body: "As vice chair of ASHRAE TC 7.4, Dr. Ye organized the committee meeting and chaired the seminar 'Energy Rationality with Waste Heat for District Heating and Cooling.'",
    link: "https://tpc.ashrae.org/Membership?cmtKey=a4ceec6a-bc2d-4979-ad3d-2a2919357246",
  },

  {
    date: "2024-09-26",
    kind: "Recognition",
    title: "Dr. Ye selected as an innovator for Berkeley Lab IMPEL 2025 cohort",
    body: "Dr. Ye joined Berkeley Lab's IMPEL program as an innovator in the 2025 cohort focused on energy and sustainability innovation.",
    link: "https://impel.lbl.gov/cohorts/innovator-cohort-6",
  },

  {
    date: "2024-09-20",
    kind: "Editorial",
    title: "Dr. Ye became guest editor for JBPS special issue",
    body: "Dr. Ye started serving as guest editor for the Journal of Building Performance Simulation special issue on building sustainability and performance through simulation.",
    link: "#",
  },

  {
    date: "2024-07-09",
    kind: "Editorial",
    title: "Dr. Ye selected as Youth Editor for Building Simulation journal",
    body: "Dr. Ye joined the editorial team of Building Simulation: An International Journal as a Youth Editor.",
    link: "#",
  },

  {
    date: "2024-06-23",
    kind: "Professional Service",
    title: "Dr. Ye began a new role as vice chair of ASHRAE TC 7.4",
    body: "After completing the research committee chair role, Dr. Ye transitioned to vice chair of ASHRAE Technical Committee 7.4.",
    link: "https://tpc.ashrae.org/Membership?cmtKey=a4ceec6a-bc2d-4979-ad3d-2a2919357246",
  },

  {
    date: "2024-06-12",
    kind: "Editorial",
    title: "Dr. Ye became guest editor for Building and Environment special issue",
    body: "The special issue focuses on net-zero carbon built environments and sustainable building performance research.",
    link: "https://www.sciencedirect.com/journal/building-and-environment/about/call-for-papers#net-zero-carbon-built-environment",
  },

  {
    date: "2024-05-30",
    kind: "Workshop",
    title: "Dr. Ye presented EV adoption impacts at UTK workshop",
    body: "Dr. Ye participated in the workshop 'Understanding Potential EV Charging Behavior and Infrastructure' and presented perspectives on EV adoption impacts on buildings.",
    link: "#",
  },

  {
    date: "2024-05-23",
    kind: "Conference",
    title: "Dr. Ye received the IBPSA-USA 2024 Emerging Contributor Award",
    body: "At SimBuild 2024 in Denver, Dr. Ye chaired multiple sessions, delivered two presentations, and received the IBPSA-USA Emerging Contributor Award.",
    link: "https://www.ibpsa.us/awards/",
  },

  {
    date: "2024-05-17",
    kind: "Student Achievement",
    title: "Ryunhee (Luna) Kim passed the Ph.D. qualifying examination",
    body: "Congratulations to Ryunhee (Luna) Kim on successfully completing the Ph.D. qualifying examination milestone.",
    link: "#",
  },

  {
    date: "2024-04-11",
    kind: "Talk",
    title: "Dr. Ye delivered a guest webinar at the University of Oklahoma",
    body: "The invited talk, 'Innovations in Modeling Sustainable Buildings,' was presented through the GSC@GCOE webinar series.",
    link: "#",
  },

  {
    date: "2024-04-08",
    kind: "Media",
    title: "Dr. Ye interviewed on sustainability goals for Alabama's new arena",
    body: "Dr. Ye discussed environmental sustainability strategies for Alabama's proposed new arena in an interview with The Crimson White.",
    link: "https://thecrimsonwhite.com/114369/opinion/opinion-alabamas-new-arena-must-champion-environmental-sustainability/",
  },

  {
    date: "2024-03-31",
    kind: "Publication",
    title: "ASHRAE/IBPSA-USA SimBuild 2022 special issue published",
    body: "The Building Performance Analysis Conference and SimBuild 2022 special issue guest edited by Dr. Ye has officially been published.",
    link: "https://doi.org/10.1080/23744731.2024.2333676",
  },
];

const AWARDS = [
  { year: "02/24/2025", who: "Dr. Yunyang Ye", what: "ASHRAE New Investigator Award", where: "ASHRAE" },
  { year: "05/21/2024", who: "Dr. Yunyang Ye", what: "2024 Emerging Contributor Award", where: "IBPSA-USA" },
];

const GALLERY = [
  { id: "g1", label: "05/10/2024 · Group Lunch @ Big Bad Breakfast",          photo: "assets/gallery/img-1.jpg", size: "wide",   tag: "People" },
  { id: "g2", label: "12/14/2024 · Group Lunch @ KPOT Korean BBQ & Hot Pot",  photo: "assets/gallery/img-2.jpg", size: "wide",   tag: "People" },
  { id: "g3", label: "03/05/2026 · Career Day @ Wheat Ridge High School",      photo: "assets/gallery/img-3.jpg", size: "square", tag: "Outreach" },
  { id: "g4", label: "03/05/2026 · Career Day @ Wheat Ridge High School",      photo: "assets/gallery/img-4.jpg", size: "square", tag: "Outreach" },
  { id: "g5", label: "03/05/2026 · Career Day @ Wheat Ridge High School",      photo: "assets/gallery/img-5.jpg", size: "square", tag: "Outreach" },
  { id: "g6", label: "Dr. Yunyang Ye Award @ IBPSA 2024",                       photo: "assets/gallery/img-6.jpg", size: "square", tag: "Award", portrait: true },
];

Object.assign(window, {
  LAB, MANIFESTO, RESEARCH_AREAS, MEMBERS, ALUMNI, PUBLICATIONS, NEWS, AWARDS, GALLERY,
});
